# Generated by Django 4.2.2 on 2023-06-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_gato_gato1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gato1',
        ),
    ]
